fortanix: add support for Fortanix SDKMS
minio/kes pull request #151
Opened 2021-09-17 09:33 UTC by aead

This commit adds a Fortanix SDKMS keystore
backend. Now, Fortanix SDKMS can be used
to store and fetch keys.

This commit only implements a single authentication
method: API keys. It does not support other authentication
methods like JWT, LDAP, Google Service Accounts, ...

A minimal KES<--->Fortanix configuration may be:
```
root: 3ecfcdf38fcbe141ae26a1030f81e96b753365a46760ae6b578698a97c59fd22

tls:
  key: private.key
  cert: public.crt

keystore:
  fortanix:
    sdkms:
      endpoint: "https://sdkms.fortanix.com"
      credentials:
        key: "NWMyMWZlNzktZDRmZS00NDFhLWFjMzMtNjZmY2U0Y2ViMThhOnVpUElyWUlhc2FIdkExLVRUOXJFa0ZpSnVPaVpEQTFKZ2hzYUZGT29mcmd3UEJwUnZmcmM0REJzd2UwTk5vSF9oU3BzTGlJN0o2Z3JUTEFPaVR0bV9B"
```

2021-09-17 15:38 UTC, harshavardhana requested changes

2021-09-17 15:38 UTC, harshavardhana commented on internal/fortanix/keystore.go
> +package fortanix
License header @aead

2021-09-17 23:30 UTC, aead commented on internal/fortanix/keystore.go
> +package fortanix
Oh, thanks 👍 - fixed!

2021-09-21 22:26 UTC, harshavardhana approved these changes

2021-09-21 22:26 UTC, merged